Revert JSONField DB migration
Running 'tethys db migrate' failed on my local dev system. It didn't like 0001_initial_41.py.
    django.db.migrations.exceptions.NodeNotFoundError: Migration uit_plus_job.0001_initial_41 dependencies reference nonexistent parent node ('tethys_compute', '0001_initial_41')
I don't know why Django wanted to run an initial database file. Also, does that 41 signify Tethys 4.1? I'm still on 4.0.
I removed that file, and 'tethys db migrate' then failed on 0008_auto_20230310_1657.py:19, which is where it tries to dump data in order to migrate from ArrayField to JSONField.
    TypeError: PbsScript.__init__() takes from 6 to 11 positional arguments but 47 were given

I don't know why that fails, so I reverted all JSONField back to ArrayField, removed the new migration files, and ran a new makemigration.